import json
import logging
import os
from typing import Any, Dict, Optional

from dotenv import load_dotenv
import httpx

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), ".env"))
load_dotenv()

logger = logging.getLogger(__name__)



class LLMClient:
    """Unified LLM Client supporting Google Gemini API with fallback to local Ollama."""

    def __init__(self, host: Optional[str] = None, default_model: str = "gemini-flash-latest"):
        self.gemini_api_key = os.getenv("GEMINI_API_KEY")
        self.host = host or os.getenv("OLLAMA_HOST", "http://localhost:11434")
        self.default_model = os.getenv("OLLAMA_MODEL", "codellama")
        self.gemini_model = os.getenv("GEMINI_MODEL", "gemini-flash-latest")
        self.timeout = float(os.getenv("OLLAMA_TIMEOUT_SECONDS", "300"))
        self._gemini_client = None

        if self.gemini_api_key:
            try:
                from google import genai
                self._gemini_client = genai.Client(api_key=self.gemini_api_key)
                logger.info(f"Google Gemini client initialized (model={self.gemini_model}).")
            except Exception as e:
                logger.warning(f"Failed to initialize Google Gemini client: {e}")

    async def generate(
        self,
        prompt: str,
        system: Optional[str] = None,
        model: Optional[str] = None,
        temperature: float = 0.2,
        num_predict: Optional[int] = 400
    ) -> str:
        """Synthesize HCL or markdown using Google Gemini, falling back to Ollama or templates."""
        # 1. Primary: Google Gemini API if key is present
        if self._gemini_client:
            try:
                logger.info(f"Dispatching Gemini generate request (model={self.gemini_model}, prompt_len={len(prompt)})")
                from google.genai import types
                config = types.GenerateContentConfig(
                    temperature=temperature,
                    max_output_tokens=num_predict or 2048,
                    system_instruction=system if system else None
                )
                response = self._gemini_client.models.generate_content(
                    model=self.gemini_model,
                    contents=prompt,
                    config=config
                )
                if response and response.text:
                    return response.text.strip()
            except Exception as e:
                logger.warning(f"Gemini generation error ({e}), falling back to Ollama / templates.")

        # 2. Secondary: Local Ollama LLM
        target_model = model or self.default_model
        options: Dict[str, Any] = {"temperature": temperature}
        if num_predict is not None:
            options["num_predict"] = num_predict
        payload = {
            "model": target_model,
            "prompt": prompt,
            "stream": False,
            "options": options,
            "keep_alive": "30m"
        }
        if system:
            payload["system"] = system

        logger.info(f"Dispatching Ollama generate request (model={target_model}, prompt_len={len(prompt)})")

        try:
            timeout_config = httpx.Timeout(self.timeout, connect=1.5)
            async with httpx.AsyncClient(timeout=timeout_config) as client:
                resp = await client.post(f"{self.host}/api/generate", json=payload)
                if resp.status_code == 200:
                    data = resp.json()
                    return data.get("response", "").strip()
                else:
                    logger.warning(f"Ollama API returned status {resp.status_code}")
        except Exception as e:
            logger.info(f"Ollama offline or unavailable ({e}); using fast deterministic synthesis template.")

        # 3. Tertiary: Deterministic safe template fallback
        return f"# Generated by fallback template (LLM offline)\n# Model: {target_model}\n"

    async def generate_json(
        self,
        prompt: str,
        system: Optional[str] = None,
        model: Optional[str] = None
    ) -> Dict[str, Any]:
        """Generate structured JSON output."""
        raw = await self.generate(prompt, system=system, model=model)
        try:
            return json.loads(raw)
        except Exception:
            clean = raw.replace("```json", "").replace("```", "").strip()
            try:
                return json.loads(clean)
            except Exception:
                return {"raw_response": raw}


# Backward-compatible alias for existing agent and service imports
LLMClient = LLMClient
OllamaClient = LLMClient
ollama_client = LLMClient()


