# Generated by TerraAgent - import blocks for existing AWS resources.
# Review before use. `terraform plan` shows these as "will be imported"; nothing is
# imported until someone applies this configuration in their own pipeline.
# TerraAgent never runs apply or import.

import {
  to = aws_route_table.rtb_003b648347930edfc_24811887
  id = "rtb-003b648347930edfc"
}
