"""Terraform `import {}` blocks for every managed resource (imports.tf).

Import IDs come only from the fixed lookup table in tools/infra_model.py -
never from an LLM. Blocks are ordered by the adoption plan's dependency-safe
import order.

Safety (CLAUDE.md rule #2): these are reviewable text. An import block only
takes effect when someone applies the configuration in their own pipeline;
TerraAgent never applies. `terraform plan` (plan equivalence, the
generate-config-out cross-check) only reads - it shows "will be imported"
without touching state or AWS.
"""

import json
from typing import Dict, List, Optional, Sequence

IMPORTS_FILENAME = "imports.tf"


class ImportEntry:
    __slots__ = ("resource_id", "address", "import_id")

    def __init__(self, resource_id: str, address: str, import_id: str):
        self.resource_id = resource_id
        self.address = address
        self.import_id = import_id


def order_entries(entries: Sequence[ImportEntry], import_order: Optional[Sequence[str]]) -> List[ImportEntry]:
    """Adoption-plan order first (dependencies before dependents), then any
    remaining entries sorted by address - fully deterministic."""
    rank = {rid: i for i, rid in enumerate(import_order or [])}
    return sorted(entries, key=lambda e: (rank.get(e.resource_id, len(rank)), e.address))


def compose_imports_tf(entries: Sequence[ImportEntry], import_order: Optional[Sequence[str]] = None) -> str:
    ordered = order_entries(entries, import_order)
    lines = [
        "# Generated by TerraAgent - import blocks for existing AWS resources.",
        "# Review before use. `terraform plan` shows these as \"will be imported\"; nothing is",
        "# imported until someone applies this configuration in their own pipeline.",
        "# TerraAgent never runs apply or import.",
    ]
    for e in ordered:
        lines.append("")
        lines.append("import {")
        lines.append(f"  to = {e.address}")
        # json.dumps gives a correctly escaped HCL string literal.
        lines.append(f"  id = {json.dumps(e.import_id)}")
        lines.append("}")
    return "\n".join(lines) + "\n"


def filter_imports_tf(imports_tf: str, addresses: Sequence[str]) -> Optional[str]:
    """imports.tf reduced to the given addresses (original order kept), or None
    if none remain - e.g. for a single-wave PR, whose import blocks must only
    target resources that PR actually contains."""
    keep = set(addresses)
    entries = [ImportEntry(a, a, i) for a, i in import_targets(imports_tf).items() if a in keep]
    if not entries:
        return None
    # resource_id doubles as the address here, and the existing order is the rank.
    return compose_imports_tf(entries, [e.resource_id for e in entries])


def import_targets(imports_tf: str) -> Dict[str, str]:
    """address -> import id, parsed back out of an imports.tf."""
    targets: Dict[str, str] = {}
    to: Optional[str] = None
    for raw in imports_tf.splitlines():
        line = raw.strip()
        if line.startswith("to"):
            to = line.split("=", 1)[1].strip()
        elif line.startswith("id") and to:
            targets[to] = json.loads(line.split("=", 1)[1].strip())
            to = None
    return targets
