"""Vetted container recipes for projects that ship without a Dockerfile
(design doc §6, container targets).

TerraAgent never builds images itself: these files go into source.zip and the
image is built by CodeBuild inside the customer's account. Nothing from the
upload becomes Dockerfile syntax except values that pass a strict pattern
(a relative file path, a module name, an integer port) and are always written
inside JSON-array CMD form - never through a shell. No LLM is involved.
"""

import json
import os
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from deploy.analyzer import ProjectProfile

NODE_VERSIONS = ("18", "20", "22")
DEFAULT_NODE = "20"
PYTHON_VERSIONS = ("3.10", "3.11", "3.12", "3.13")
DEFAULT_PYTHON = "3.12"

# public.ecr.aws mirrors Docker Hub's official images without its pull rate limits.
NODE_IMAGE = "public.ecr.aws/docker/library/node:{version}-slim"
PYTHON_IMAGE = "public.ecr.aws/docker/library/python:{version}-slim"

ENTRYPOINT_FILE = ".terraagent-entrypoint.sh"

_SAFE_PATH = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_./-]{0,200}$")
_SAFE_MODULE = re.compile(r"^[A-Za-z_][A-Za-z0-9_.]{0,200}$")
_PY_APP = re.compile(r"(?m)^(\w+)\s*=\s*(FastAPI|Flask)\(")
_NODE_LOCAL_BIND = re.compile(r"\.listen\([^)]*['\"](?:localhost|127\.0\.0\.1)['\"]")
_DEV_RUNNERS = ("nodemon", "ts-node", "tsx watch", "next dev", "vite")


class DockerfileError(ValueError):
    """The project can't be containerised with a vetted recipe. Safe to show."""


@dataclass
class GeneratedContainer:
    files: Dict[str, str] = field(default_factory=dict)  # path relative to the app dir -> content
    command: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


def _safe_path(path: str) -> str:
    if not _SAFE_PATH.match(path) or ".." in path.split("/"):
        raise DockerfileError(f"The entry file path '{path[:80]}' can't be used in a generated Dockerfile.")
    return path


def _read(app_root: str, rel: str) -> str:
    full = os.path.join(app_root, *rel.split("/"))
    try:
        with open(full, "rb") as f:
            return f.read(1024 * 1024).decode("utf-8", errors="replace")
    except OSError:
        return ""


def _entry_file(profile: ProjectProfile) -> Optional[str]:
    for ev in profile.get("evidence", {}).get("server_entrypoint", []):
        if ev.get("file") and ev["file"] != "package.json":
            return ev["file"]
    return None


_SAFE_TOKEN = re.compile(r"^[A-Za-z0-9:_.-]{1,40}$")


def entrypoint_script(runtime: str, migrate: Optional[List[str]] = None) -> str:
    """sh wrapper that builds DATABASE_URL from the DB_* variables ECS injects
    (the password comes from the RDS-managed secret at task start, so neither
    TerraAgent nor Terraform state ever holds it). URL-encodes user and password.

    With `migrate` (one of deploy.fullstack._migration's fixed forms), runs it
    before the server when TERRAAGENT_RUN_MIGRATIONS=true; a failed or slow
    migration is logged and the app still starts."""
    if migrate and not all(_SAFE_TOKEN.match(t) for t in migrate):
        raise DockerfileError("The detected migration command can't be used in a generated entrypoint.")
    if runtime == "node":
        encoder = (
            "node -e 'const e=encodeURIComponent,p=process.env;"
            "process.stdout.write(`${p.DB_URL_SCHEME}://${e(p.DB_USER)}:${e(p.DB_PASSWORD)}@${p.DB_HOST}:${p.DB_PORT}/${p.DB_NAME}`)'"
        )
    else:
        encoder = (
            "python -c 'import os,urllib.parse as u;e=lambda v:u.quote(v,safe=\"\");p=os.environ;"
            "print(p[\"DB_URL_SCHEME\"]+\"://\"+e(p[\"DB_USER\"])+\":\"+e(p[\"DB_PASSWORD\"])+\"@\"+p[\"DB_HOST\"]"
            "+\":\"+p[\"DB_PORT\"]+\"/\"+p[\"DB_NAME\"],end=\"\")'"
        )
    script = (
        "#!/bin/sh\n"
        "# Generated by TerraAgent: builds DATABASE_URL from the DB_* variables that ECS\n"
        "# injects (DB_PASSWORD comes from the RDS-managed secret in Secrets Manager).\n"
        "set -e\n"
        'if [ -z "$DATABASE_URL" ] && [ -n "$DB_HOST" ] && [ -n "$DB_PASSWORD" ]; then\n'
        f'  DATABASE_URL="$({encoder})"\n'
        "  export DATABASE_URL\n"
        "fi\n"
    )
    if migrate:
        command = " ".join(migrate)
        script += (
            'if [ "${TERRAAGENT_RUN_MIGRATIONS:-false}" = "true" ]; then\n'
            f'  echo "TerraAgent: running {command}"\n'
            f'  timeout 300 {command} || echo "TerraAgent: {command} failed; starting the app anyway"\n'
            "fi\n"
        )
    return script + 'exec "$@"\n'


def _cmd(command: List[str]) -> str:
    return "CMD " + json.dumps(command)


def _node(app_root: str, profile: ProjectProfile, port: int, with_db: bool,
          migrate: Optional[List[str]] = None) -> GeneratedContainer:
    out = GeneratedContainer()
    version = profile.get("runtime_version") or DEFAULT_NODE
    if version not in NODE_VERSIONS:
        out.warnings.append(f"Node {version} isn't a supported base image; using Node {DEFAULT_NODE}.")
        version = DEFAULT_NODE
    try:
        pkg = json.loads(_read(app_root, "package.json") or "{}")
    except json.JSONDecodeError:
        pkg = {}
    scripts = pkg.get("scripts") if isinstance(pkg.get("scripts"), dict) else {}
    start = str(scripts.get("start") or "")
    has_build = bool(scripts.get("build"))
    entry = _entry_file(profile)

    if start:
        out.command = ["npm", "start"]
        if any(runner in start for runner in _DEV_RUNNERS):
            out.warnings.append(
                f"package.json's start script uses a development runner ('{start[:60]}'). "
                "Dev dependencies are kept so it runs, but a production start script (node dist/index.js) is better."
            )
    elif entry and entry.endswith((".js", ".mjs", ".cjs")):
        out.command = ["node", _safe_path(entry)]
    else:
        raise DockerfileError(
            "Couldn't work out how to start the server: add a \"start\" script to package.json "
            "(for example \"node server.js\") or include a Dockerfile."
        )
    # Keep dev dependencies when the server runs TypeScript straight from source
    # (tsx, ts-node) or starts through a dev dependency, and when the migration
    # tool is one (drizzle-kit, prisma): pruning them would break the container.
    dev = pkg.get("devDependencies") if isinstance(pkg.get("devDependencies"), dict) else {}
    start_tool = next((t for t in start.split() if "=" not in t), "")
    keep_dev = bool(
        any(runner in start for runner in _DEV_RUNNERS)
        or re.search(r"\b(tsx|ts-node)\b", start)
        or start_tool in dev
        or (migrate and migrate[0] in ("npm", "npx") and any(k in dev for k in ("drizzle-kit", "prisma", "knex", "sequelize-cli")))
    )
    if entry and _NODE_LOCAL_BIND.search(_read(app_root, entry)):
        out.warnings.append(
            f"{entry} listens on localhost only, so the load balancer can't reach it. Listen on 0.0.0.0 "
            "(or omit the host argument)."
        )

    # NODE_ENV is set only after installing: with NODE_ENV=production, npm skips
    # devDependencies, and build tools (vite, tsc, esbuild) usually live there.
    install = "npm ci --include=dev" if profile.get("has_lockfile") else "npm install --include=dev"
    if has_build:
        steps = f"{install} && npm run build" + ("" if keep_dev else " && npm prune --omit=dev")
    else:
        steps = ("npm ci" if profile.get("has_lockfile") else "npm install") + ("" if keep_dev else " --omit=dev")

    lines = [
        "# Generated by TerraAgent (vetted template): the project had no Dockerfile.",
        f"FROM {NODE_IMAGE.format(version=version)}",
        "WORKDIR /app",
        "COPY --chown=node:node . .",
        f"RUN {steps}",
        "ENV NODE_ENV=production",
    ]
    if with_db:
        lines.append(f"RUN chmod 0755 /app/{ENTRYPOINT_FILE}")
    lines += ["USER node", f"EXPOSE {int(port)}"]
    if with_db:
        lines.append(f'ENTRYPOINT ["/app/{ENTRYPOINT_FILE}"]')
    lines.append(_cmd(out.command))
    out.files["Dockerfile"] = "\n".join(lines) + "\n"
    if with_db:
        out.files[ENTRYPOINT_FILE] = entrypoint_script("node", migrate)
    return out


def _py_module(path: str) -> str:
    module = path[:-3].replace("/", ".")
    if not _SAFE_MODULE.match(module):
        raise DockerfileError(f"'{path[:80]}' isn't importable as a Python module.")
    return module


def _python(app_root: str, paths: List[str], profile: ProjectProfile, port: int, with_db: bool,
            migrate: Optional[List[str]] = None) -> GeneratedContainer:
    out = GeneratedContainer()
    version = profile.get("runtime_version") or DEFAULT_PYTHON
    if version not in PYTHON_VERSIONS:
        out.warnings.append(f"Python {version} isn't a supported base image; using Python {DEFAULT_PYTHON}.")
        version = DEFAULT_PYTHON
    deps = {d.lower().replace("_", "-") for d in profile.get("dependencies", [])}
    manifest = profile.get("dependency_manifest") or ""
    if manifest.startswith("unsupported:"):
        raise DockerfileError(
            f"Dependencies are declared in {manifest.split(':', 1)[1]}; add a requirements.txt or include a Dockerfile."
        )
    p = str(int(port))

    if "manage.py" in paths:
        wsgi = next((x for x in sorted(paths) if x.endswith("/wsgi.py") and x.count("/") == 1), None)
        if "gunicorn" in deps and wsgi:
            out.command = ["gunicorn", "--bind", f"0.0.0.0:{p}", f"{_py_module(wsgi)}:application"]
        else:
            out.command = ["python", "manage.py", "runserver", f"0.0.0.0:{p}", "--noreload"]
            out.warnings.append("Django will run with its development server; add gunicorn to requirements.txt for production.")
    else:
        app_ref: Optional[str] = None
        kind = ""
        for path in sorted(x for x in paths if x.endswith(".py") and x.count("/") < 3):
            if m := _PY_APP.search(_read(app_root, path)):
                app_ref, kind = f"{_py_module(path)}:{m.group(1)}", m.group(2)
                break
        if app_ref and kind == "FastAPI" and "uvicorn" in deps:
            out.command = ["uvicorn", app_ref, "--host", "0.0.0.0", "--port", p]
        elif app_ref and kind == "Flask" and "gunicorn" in deps:
            out.command = ["gunicorn", "--bind", f"0.0.0.0:{p}", app_ref]
        else:
            entry = _entry_file(profile)
            if not entry or not entry.endswith(".py"):
                raise DockerfileError("Couldn't find the file that starts the server; include a Dockerfile.")
            out.command = ["python", _safe_path(entry)]
            text = _read(app_root, entry)
            if "app.run(" in text and "0.0.0.0" not in text:
                out.warnings.append(
                    f"{entry} calls app.run() without host='0.0.0.0', so it only listens on localhost inside the "
                    "container. Pass host='0.0.0.0' or add gunicorn to requirements.txt."
                )

    if manifest == "requirements.txt":
        install = ["COPY requirements.txt ./", "RUN pip install --no-cache-dir -r requirements.txt", "COPY . ."]
    else:
        install = ["COPY . .", "RUN pip install --no-cache-dir ."]
    lines = [
        "# Generated by TerraAgent (vetted template): the project had no Dockerfile.",
        f"FROM {PYTHON_IMAGE.format(version=version)}",
        "WORKDIR /app",
        "ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1",
        *install,
        "RUN useradd --create-home --uid 10001 app && chown -R app /app",
    ]
    if with_db:
        lines.append(f"RUN chmod 0755 /app/{ENTRYPOINT_FILE}")
    lines += ["USER app", f"EXPOSE {p}"]
    if with_db:
        lines.append(f'ENTRYPOINT ["/app/{ENTRYPOINT_FILE}"]')
    lines.append(_cmd(out.command))
    out.files["Dockerfile"] = "\n".join(lines) + "\n"
    if with_db:
        out.files[ENTRYPOINT_FILE] = entrypoint_script("python", migrate)
    return out


def generate(app_root: str, paths: List[str], profile: ProjectProfile, port: int, with_db: bool = False,
             migrate: Optional[List[str]] = None) -> GeneratedContainer:
    """Dockerfile (+ DATABASE_URL entrypoint when `with_db`, which also runs
    `migrate` when enabled) for a server project without one. `paths` are
    relative to `app_root`."""
    if profile["runtime"] == "node":
        return _node(app_root, profile, port, with_db, migrate)
    if profile["runtime"] == "python":
        return _python(app_root, paths, profile, port, with_db, migrate)
    raise DockerfileError(f"No vetted container recipe for a '{profile['runtime']}' project; include a Dockerfile.")
